### PR TITLE
Contrib

### PR DESCRIPTION
**Pull request by bakhtvar**
Openjpeg 2.5 proposed as replacement of older version. keeping maximum backward compatibility.
port is applied for Win64 (Linux & Mac) shall be compiled separately.

### CODE REVIEW

**Comment by jaime-olivares** [comment]
Hi @bakhtvar,
Your pull request has a lot of issues and reverts all the improvements we made for having a simplified cross-platform code.
This kind of massive alteration should be discussed first extensively to see the pros and cons.

**Comment by bakhtvar** [comment]
It's tried the best to keep/handle even the code-style change between opj1.5.3...opj2.5, such that fo-dicom.Codecs doesn't sense such massive change.
Would you please point any reverted improvements?
I believe no need to discuss that this a must to keep the lib updated asap. While opj>2.3 is offering multi-threading which is a basic need to extra-large dicom images (MG/Digital Pathology), so some body need to take action for this lift.

**Comment by jaime-olivares** [comment]
We are closing this pull request as we are working on our own with a stable version of OpenJPEG and support for all OS.

However, it has been helpful to review your source code to understand some changes in the library.

**Comment by bakhtvar** [comment]
Good to hear from you.
Just please know that my PR is working for more than a year know, also had
some fixes in openjpeg code as well! due to problem it had for super small
dimentions ( less that 32pixel I guess)..

My PR is not formed well as I did it in less that 48 hours in rush. But it
works : D.

Regards

**Pull request closed without merging**
